language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests  --with-coverage week_1/
after_success:
  - coveralls
